In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
mat = torch.tensor([[7,8],
                    [8,9]])
mat

tensor([[7, 8],
        [8, 9]])

In [ ]:
mat.ndim

2

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
# Tensor
ts = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
ts

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
ts.ndim

3

In [ ]:
ts.shape

torch.Size([1, 3, 3])

In [ ]:
rand_ts = torch.rand(size = (3,4))
rand_ts, rand_ts.dtype

(tensor([[0.0620, 0.8815, 0.8870, 0.3475],
         [0.1386, 0.9894, 0.0896, 0.9075],
         [0.2317, 0.8141, 0.7108, 0.1005]]),
 torch.float32)

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input = zero_to_ten) # same shape as another tensor
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py'>

In [ ]:
ten_zeros.shape, ten_zeros.dtype, ten_zeros.device

(torch.Size([10]), torch.int64, device(type='cpu'))

In [ ]:
torch.multiply(ones, 10)

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 6.61 ms


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 1.25 ms, sys: 0 ns, total: 1.25 ms
Wall time: 1.2 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor) # so much faster

CPU times: user 131 µs, sys: 6 µs, total: 137 µs
Wall time: 144 µs


tensor(14)

In [ ]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]], dtype = torch.float32)

output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')

print(f'Mean: {x.type(torch.float32).mean()}')
print(f'Sum: {x.sum()}')

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'